config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :foods
    end
  end
  resources :jobs
  resources :foods
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
  validates :ate_at, presence: true, length: { maximum: 255 }
  validates :fat, presence: true, length: { maximum: 255 }
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
  validates :burn_at, presence: true, length: { maximum: 255 }
  validates :calorie, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :jobs
  has_many :foods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
    def counts(user)
    @count_jobs = user.jobs.count
    @count_foods = user.foods.count
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @foods = current_user.foods.all
  end
  
  def show
    @food = Food.find(params[:id])
  end
  
  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.build(food_params)
    if @food.save
      flash[:success] = 'メニューを投稿しました。'
      redirect_to root_url
    else
      @foods = current_user.foods.order('created_at DESC').page(params[:page])
      flash.now[:danger] = 'メニューの投稿に失敗しました。'
      render 'toppages/index'
    end
  end
  
  def edit
    @food = Food.find(params[:id])
  end

  def update
    if @food.update(food_params)
      flash[:success] = 'メニュー は正常に更新されました'
      redirect_to @food
    else
      flash.now[:danger] = 'メニュー は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @food.destroy
    flash[:success] = 'メニューを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def set_foods
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:ate_at,:content,:fat)
  end

  def correct_user
    @food = current_user.foods.find_by(id: params[:id])
    unless @food
      redirect_to root_url
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @jobs = current_user.jobs.all
  end
  
  def show
    @job = Job.find(params[:id])
  end
  
  def new
    @job = Job.new
  end
  
  
  def create
    @job = current_user.jobs.build(job_params)
    if @job.save
      flash[:success] = 'メニューを投稿しました。'
      redirect_to root_url
    else
      @jobs = current_user.jobs.order('created_at DESC').page(params[:page])
      flash.now[:danger] = 'メニューの投稿に失敗しました。'
      render 'toppages/index'
    end
  end
  
  def edit
    @job = Job.find(params[:id])
  end

  def update
    if @job.update(job_params)
      flash[:success] = 'メニュー は正常に更新されました'
      redirect_to @job
    else
      flash.now[:danger] = 'メニュー は更新されませんでした'
      render :edit
    end
  end
  

  def destroy
    @job.destroy
    flash[:success] = 'メニューを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
    private
    
  def set_jobs
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:burn_at,:content,:calorie)
  end

  def correct_user
    @job = current_user.jobs.find_by(id: params[:id])
    unless @job
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @user = current_user
      @job = current_user.jobs.build  # form_for 用
      @jobs = current_user.jobs.order('created_at DESC').page(params[:page])
      @foods = current_user.foods.build  # form_for 用
      @foods = current_user.foods.order('created_at DESC').page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  def index
    @users = User.all.page(params[:page])
  end

  def show
    # jobs 用
    @user = User.find(params[:id])
    @jobs = @user.jobs.order('created_at DESC').page(params[:page])
    counts(@user)
    @point = @user.jobs.sum(:calorie)
  end

  def foods
    # foods 用
    @user = User.find(params[:id])
    @foods = @user.foods.order('created_at DESC').page(params[:page])
    counts(@user)
    @point = @user.foods.sum(:fat)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
   private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/foods/_foods.html.erb
<ul class="media-list">
  <% foods.each do |food| %>
    <li class="media">
      <div class="media-left">
        <img class="media-object img-rounded" src="<%= gravatar_url(food.user, options = { size: 50 }) %>" alt="">
      </div>
      <div class="media-body">
        <div>
          <%= link_to food.user.name, user_path(food.user) %> <span class="text-muted">posted at <%= food.created_at %></span>
        </div>
        <div>
          <p><%= food.ate_at %></p>
          <p><%= food.content %></p>
          <p><%= food.fat %></p>
        </div>
        <div>
          <% if current_user == food.user %>
            <%= link_to "Delete", food, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
            <%= link_to 'edit', edit_food_path(food), class: "btn btn-default" %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate foods %>
</ul>

app/views/foods/_form.html.erb
<div class="row">
 <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
   <%= form_for(food) do |f| %>

    <% if food.errors.any? %>
     <div class="alert alert-warning">
      <ul>
       <% food.errors.full_messages.each do |food| %>
       <li><%= food %></li>
       <% end %>
      </ul>
     </div>
    <% end %>
    
      <div class="form-group">
      <%= f.label :ate_at, "日時" %>
      <%= f.text_field :ate_at, class: "form-control" %>
      </div>
 
     <div class="form-group">
      <%= f.label :content, "メニュー" %>
      <%= f.text_field :content, class: "form-control" %>
     </div>
     
      <div class="form-group">
      <%= f.label :fat, "カロリー" %>
      <%= f.text_field :fat, class: "form-control" %>
     </div>
  

  <%= f.submit "投稿", class: "btn btn-primary btn-block" %>

   <% end %>
 </div>
</div>

app/views/foods/edit.html.erb
<h1>id: <%= @food.id %> の編集ページ</h1>

<%= render "form", food: @food %>

app/views/foods/index.html.erb
<h1>一覧</h1>

<% if @foods.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>日時</th>
        <th>内容</th>
        <th>ポイント</th>
      </tr>
    </thead>
    <tbody>

     <% @foods.each do |food| %>
      <thead>
       <tr>
        <td><%= link_to food.id, food %></td>
        <td><%= food.ate_at %></td>
        <td><%= food.content %></td>
        <td><%= food.fat %></td>
       </tr>
    　</thead>
    
   　<% end %>
  　</tbody>
  </table>
<% end %>
 
<%= link_to '新規投稿', new_food_path, class: "btn btn-primary " %>

app/views/foods/new.html.erb
<h1>新規作成ページ</h1>

<%= render "form", food: @food %>

app/views/foods/show.html.erb
<h1>id: <%= @food.id %> 詳細ページ</h1>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @food.id %></td>
  </tr>
  <tr>
    <th>日時</th>
    <td><%= @food.ate_at %></td>
    <th>食事</th>
    <td><%= @food.content %></td>
    <th>ポイント</th>
    <td><%= @food.fat %></td>
  </tr>
</table>

<%= link_to '編集', edit_food_path(@food), class: "btn btn-default" %>
<%= link_to '削除', @food, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: "btn btn-danger" %>

app/views/jobs/_form.html.erb
<div class="row">
 <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
   <%= form_for(job) do |f| %>

    <% if job.errors.any? %>
     <div class="alert alert-warning">
      <ul>
       <% job.errors.full_messages.each do |job| %>
       <li><%= job %></li>
       <% end %>
      </ul>
     </div>
    <% end %>
    
    
     <div class="form-group">
      <%= f.label :burn_at, "日時" %>
      <%= f.text_field :burn_at, class: "form-control" %>
     </div>
 
     <div class="form-group">
      <%= f.label :content, "内容" %>
      <%= f.text_field :content, class: "form-control" %>
     </div>
     
     <div class="form-group">
      <%= f.label :calorie, "ポイント" %>
      <%= f.text_field :calorie, class: "form-control" %>
     </div>
  

  <%= f.submit "投稿", class: "btn btn-primary btn-block" %>

   <% end %>
 </div>
</div>

app/views/jobs/_jobs.html.erb
<ul class="media-list">
  <% jobs.each do |job| %>
    <li class="media">
      <div class="media-left">
        <img class="media-object img-rounded" src="<%= gravatar_url(job.user, options = { size: 50 }) %>" alt="">
      </div>
      <div class="media-body">
        <div>
          <%= link_to job.user.name, user_path(job.user) %> <span class="text-muted">posted at <%= job.created_at %></span>
        </div>
        <div>
          <p><%= job.burn_at %></p>
          <p><%= job.content %></p>
          <p><%= job.calorie %></p>
        </div>
        <div>
          <% if current_user == job.user %>
            <%= link_to "Delete", job, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
            <%= link_to 'edit', edit_job_path(job), class: "btn btn-default" %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate jobs %>
</ul>

app/views/jobs/edit.html.erb
<h1>id: <%= @job.id %> の編集ページ</h1>

<%= render "form", job: @job %>

app/views/jobs/index.html.erb
<h1>一覧</h1>

<% if @jobs.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>日時</th>
        <th>内容</th>
        <th>ポイント</th>
      </tr>
    </thead>
    <tbody>

     <% @jobs.each do |job| %>
      <thead>
       <tr>
        <td><%= link_to job.id, job %></td>
        <td><%= job.burn_at %></td>
        <td><%= job.content %></td>
        <td><%= job.calorie %></td>
       </tr>
    　</thead>
    
   　<% end %>
  　</tbody>
  </table>
<% end %>
 
<%= link_to '新規投稿', new_job_path, class: "btn btn-primary " %>

app/views/jobs/new.html.erb
<h1>新規作成ページ</h1>

<%= render "form", job: @job %>

app/views/jobs/show.html.erb
<h1>id: <%= @job.id %> 詳細ページ</h1>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @job.id %></td>
  </tr>
  <tr>
  <tr>
    <th>日時</th>
    <td><%= @job.burn_at %></td>
    <th>運動</th>
    <td><%= @job.content %></td>
    <th>ポイント</th>
    <td><%= @job.calorie %></td>
  </tr>
  </tr>
  
</table>

<%= link_to '編集', edit_job_path(@job), class: "btn btn-default" %>
<%= link_to '削除', @job, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: "btn btn-danger" %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">My app</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'My profile', user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
          <% else %>
           <li><%= link_to 'Signup', signup_path %></li>
           <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>my app</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <p>ログイン完了ユーザ: <%= current_user.name %></p>
  <div class="row">
    <aside class="col-md-4">
      <p>jobs</p>
      <%= link_to '新規投稿', new_job_path, class: "btn btn-primary " %>
      <P>foods</P>
      <%= link_to '新規投稿', new_food_path, class: "btn btn-primary " %>
  </div>
    </aside>
</div>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the My app</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/foods.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Jobs <span class="badge"><%= @count_jobs %></span><% end %></li>
      <li class="<%= 'active' if current_page?(foods_user_path(@user)) %>"><%= link_to foods_user_path(@user) do %>foods <span class="badge"><%= @count_foods %></span><% end %></li>
    </ul>

    <%= render 'foods/foods', foods: @foods %>
    <%= @point %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
      
    　<% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Jobs <span class="badge"><%= @count_jobs %></span><% end %></li>
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>foods <span class="badge"><%= @count_foods %></span><% end %></li>
    </ul>
    <%= render 'jobs/jobs', jobs: @jobs %>

    <%= render 'foods/foods', foods: @foods %>
    #ポイントの合計
  </div>
</div>